name: GitHub Profile Trophy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
      timezone: "Asia/Singapore"

permissions:
  contents: write

jobs:
  generate-trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Generate trophy SVG
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: bert093
          file: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
