name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Profile
        uses: lowlighter/metrics@latest
        with:
          filename: profile.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: bert093
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Singapore
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
